export const EVENTS = {
  connection: 'connection',
  CLIENT: {
    NEW_TIMER: 'NEW_TIMER',
    GET_TIMERS: 'GET_TIMERS',
    CHECK_FOR_FINISHED_TIMERS: 'CHECK_FOR_FINISHED_TIMERS',
  },
  SERVER: {
    USER_CREATED: 'USER_CREATED',
    NEW_TIMER: 'NEW_TIMER',
    SEND_TIMERS: 'SEND_TIMERS',
    TIMER_DONE: 'TIMER_DONE',
    ERROR: 'ERROR',
  },
};
